### ISSUE TITLE
Questions about items' weight

### ISSUE THREAD

**Issue by houcem-chaabane-aqsone** [renault-iaa/challenge-roadef-2022#10]
Hi, 

In item table, we can find very big weight values. 
For instance, item 0091017300_03072022000005 from VA2 has a Weight value equal to 1354570. 
I divided it by 1000 to get the value in Kg. It gives : 1354,57 Kg. Is it correct ? 

In order to get the item's weight, do we need to multiply by the number of items ? 
For instance item 0091017300_03072022000007 from VA2 has 15 items , then it's weight will be :  15 * 307,8 Kg =  4617 kg 
Is this right ? 

Thanks in advance,
Houcem

**Comment by renault-iaa** [comment]
Hello,

Yes it is correct. There are very heavy items, especially those with such large dimensions (2400 x 1200 x 975).
If the number of items is 15 for item-id 0091017300_03072022000007, it means that you have to load 15 units of this item, each unit has a weight of 307,8 kg.

Best regards
Alain Nguyen

**Comment by houcem-chaabane-aqsone** [comment]
Thank you for your answer. 
So in conclusion these two formulas must be applied for item-id 0091017300_03072022000007  : 
Weight_of_item_id_0091017300_03072022000007_in_kg = **number_of_items** * ( weight **/ 1000**)      
Volume_of_item_id_0091017300_03072022000007_in_mm3 = **number_of_items** * ( length * width * (height+ nesting height ) )

**Comment by renault-iaa** [comment]
Concerning the formula about weight :

- In input items file, the weight is defined in kg, not grams. Maybe the misunderstanding is due to the fact that in our files, the "," is the separator for decimal and not for thousands.
- if for instance number_of_items = 5, it means that you have to load 5 items, each one with the same characteristics (length, width, height, weight etc) described in item_id. You do not load a single item with weight = 5 * weight_of_item_id.
- the right formula is :  Weight_of_item_id_0091017300_03072022000007_in_kg = weight

Concerning the formula about the volume : the nesting height is included in the height, so the right formula is : 
Volume_of_item_id_0091017300_03072022000007_in_mm3 = length * width * height
Again you have to load N duplicates of item_id, if number_of_items = N.

**Comment by vincent-gargasson-aqsone** [comment]
Hello @renault-iaa 
I have also a question regarding those columns. 
When reading the `DatasetA.zip/AS/input_truck.xlsx` and taking a look at the feature **Max weight on the bottom item in stacks** , the value displayed is 100 000 for most of the trucks.
 
If the weight is in kg as you mentionned above, it doesn't make "physical" sense to put a **Max weight on the bottom item in stacks** limit at 100 000 kg for each items (it's way too big). Do you confirm our interpretation? Or is the **Max weight on the bottom item in stacks** in grams?
Some of the items has a limit at 750 which makes sense if it's in kg so we are a bit confused.

Thanks a lot for your feedback

**Comment by renault-iaa** [comment]
Hello,

The max weight on the bottom item in stacks is in kg. The value "100 000" just means that in fact there is no constraint of max weight on the bottom item for some trucks, because of the type of packagings loaded into these trucks. These packagings can bear any weight for stacks limited otherwise by the max stack density (TEM_t).
