### ISSUE TITLE
Placement constraints

### ISSUE THREAD

**Issue by DavidGarHeredia** [renault-iaa/challenge-roadef-2022#15]
Hi!

In the PDF explaining the problem, in section 3.3.3, it is said for constraint P3:

> The business motivation is that in case the driver should brake abruptly, any stack should be retained either by another stack or by the front of the truck

And as far as I understood from the PDF, the constraint only refers to the X and Y axes. However, I think this is not enough to guarantee the desired condition. A restriction in the Z axis should also exist for that. 

Consider for instance the situation depicted in Fig 8 of the mentioned PDF. Stack "s" fulfills condition P3, but items s2 and s3 would not be retained in case of a brake. Nothing in the Z axis prevents it.

So my question is, is this the desired behavior or the description of constraint P3 is not complete?

Thanks in advance

David

**Comment by renault-iaa** [comment]
Hello David,

You are right : in the real life, stability must also be ensured in the Z axis. But we decided not to take into account the stability on the Z axis in our algorithm in production and consequently also in the challenge, because it would be too complex. Truck drivers manage to ensure the stability in the Z axis usually by fastening the items of the stacks.

Best regards
Alain Nguyen

**Comment by DavidGarHeredia** [comment]
Thanks a lot!
