### ISSUE TITLE
Inconsistent parameters on the trailers

### ISSUE THREAD

**Issue by louisv123** [renault-iaa/challenge-roadef-2022#19]
`EJ_eh `and `ej_e ` (parameter and variable related to the tractor and the trailor) seems inconsistent between the formula, the schema and the provided data:

* `EJ_eh `= 1600, `EJ_hr `= 7630 in the instance "Dataset A" but given the schema `EJ_eh `can not be lower than `EJ_hr`. It's seems `EJ_eh ` is then the "distance between the beginning of the trailer and the harness" and not "distance between the end of the trailer and the harness".

* `ej_e` is defined as "the distance between center of gravity of stacks and the end of the trailer", but since the formula is:
sum((sx_0_s + (sx_e_s-sx_0_s)/2)*sm_s)/tm_t, then  `ej_e` should be defined as "the distance between center of gravity of stacks and the beginning of the trailer"

Thank you for your answer,

**Comment by renault-iaa** [comment]
Hello, 

You are right, there was an incoherence on the semantics of EJ_eh and ej_e. We correct it in version v1.3 of the subject committed on July 27th. New definitions since v1.3 are : 
$ej^e$ : distance between center of gravity of stacks and the start of the trailer
$EJ^{eh}$ : distance between the start of the trailer and the harness

Best regards
Alain Nguyen

**Comment by fontanf** [comment]
It's still defined as "Distance between end of trailer and harness" in the PDF rules

**Comment by renault-iaa** [comment]
Sorry I forgot to rename the column in the rules. It is done in the last version of the rules I have just committed.
