### ISSUE TITLE
Density assumption 

### ISSUE THREAD

**Issue by gfpantoja** [renault-iaa/challenge-roadef-2022#30]
Hello dear organizers, 

Let's consider only the stacks composed of a single item and that we are checking the maximum stack density with these single-item stacks. I question if it is correct to assume that a single item's density is always less than or equal to the maximum stack density of the trucks that can carry that single-item stack?

**Comment by renault-iaa** [comment]
Hello,

No you cannot make such an assumption. In theory, it may occur that the single item can be loaded into 2 planned trucks (according to product code), that the 2 planned trucks have different maximum stack density (one above and one below the item's density), and finally the single item can be loaded only into 1 of the 2 trucks because of the truck's maximum stack density. Such a case should be very rare but not impossible.

**Comment by gfpantoja** [comment]
Thank you very much for your answer! :)
